---
# tasks file for web

- name: "install apache Sotware"
  package: 
        name: "{{ soft }}"
        state: present    

- name: "copy web page"
  copy:
        src: "index.html"
        dest: /var/www/html/index.html     
  register: state

- name: "start apache Service"  
  service:
        name: "{{ soft }}" 
        state: started
  when: state.changed       
