---
# tasks file for lbrole

- name: "install haproxy software"
  package: 
        name: "{{ soft }}"
        state: present

- name: "set up configuration file"
  template:
        src: "haproxy.cfg.j2"
        dest: "/etc/haproxy/haproxy.cfg"

- name: "start firewalld service"
  service: 
        name: "firewalld"
        state: started

- name: "expose proxy port"
  firewalld:
        port: "{{ port_no }}/tcp"
        state: enabled
        permanent: yes
        immediate: yes

- name: "temporary diable SELINUX"
  command: "setenforce 0"

- name: "start haproxy Service"
  service: 
        name: "{{ soft }}"
        state: started
        enabled: yes
